### ISSUE TITLE
Compiling on 10.11.3

### ISSUE THREAD

**Issue by tfr** [ElusiveMind/osx_server_enhancements#6]
Should this work on 10.11.3?

My attempt ran into:

`In file included from /Users/tfr/Downloads/osx_server_enhancements-osx-10-11-2-php-5-5-30/packages/php-5.5.30/ext/intl/php_intl.c:25:
./php_intl.h:23:10: fatal error: 'php.h' file not found
#include <php.h>
         ^
1 error generated.
make: *** [php_intl.lo] Error 1`

The php.h itself does seem to exist in ./packages/php-5.5.30/main/php.h

Is there some include path not set or set incorrectly?

**Comment by ElusiveMind** [comment]
This should work on 10.11.3 - I see I do not have a 10.11.3 branch - so I may not have tested it yet. Make sure you installed the command line tools and I will fire up a VM and check it out.

**Comment by ElusiveMind** [comment]
Just realized that 10.11.3 isn't out yet but is in beta. Let me get set up on that and try it. Might be a day or two.

**Comment by ElusiveMind** [comment]
Also looks like an issue compiling the intl extension..... interesting.

**Comment by ElusiveMind** [comment]
The branch default was set to 10.11.1 - try changing the branch to the 10.11.2 with PHP 5.5.30 and see if that works. I just tried it and it seems to work well

**Comment by tfr** [comment]
I tried with the 10.11.2 branch - this can be even seen from the error message above.

**Comment by ElusiveMind** [comment]
Did you try typing "xcode-select --install" and then re-running the installer?

**Comment by ElusiveMind** [comment]
Going to mark this as fixed given the new re-worked repository. I've tested a number of scenarios and all seems well
